### ISSUE TITLE
FTP change Dir

### ISSUE THREAD

**Issue by Ohopwood** [touki653/php-ftp-wrapper#15]
When i try to change the dir using the
   $wrapper->chdir("/folder");
It does not change and throws back a 500 internal error. 

I got the list of folders to verify the folder name was correct, using but still didn't work. 
    $wrapper->rawlist('/');
But the mkdir, and rmdir all work like there suppose to do.

**Comment by touki653** [comment]
Make sure you [display all errors](http://php.net/manual/en/function.error-reporting.php) and use a different [error handler](http://php.net/set_error_handler) if needed, (Symfony may just need to switch to DEV mode) in order to see the complete error message.

My first guess is a permission problem.
